name: Build Submission Files
on: [push]
jobs: 
  sweave-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Print R version
        run: version
        shell: Rscript {0}
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Print pdflatex version
        run: pdflatex --version
        
      